project:
  type: book

book:
  title: \SunQuarTeX Example - Book 
  author: sun123zxy
  date: 2025/11/29
  chapters:
    - index.qmd
    - part: 文章
      chapters:
        - examples/cnart.qmd
        - examples/enart.qmd

bibliography: examples/bibliography.bib

shift-heading-level-by: 0 # Seemingly Quarto will -1 automatically for books. So leave this at 0.

format:
  pdf:
    documentclass: book
    custom-theorem:
      numbered-within: chapter
      numbered-alike: true